[package]
name = "uuid-cli"
version = "1.0.0"
authors = ["Kyle Gretchev <kgretcehv@gmail.com>"]
description = "Generate UUIDs"
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
clipboard = "0.5"
uuid = { version = "0.8", features = ["v4"] }

[[bin]]
name = "uuid"
path = "src/main.rs"