[package]
name = "uuid-cli"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretcehv@gmail.com>"]

[dependencies]
uuid = { version = "0.5.0", features = ["v4"] }
clipboard = "0.3.0"
clap = "2.24.1"

[[bin]]
name = "uuid"
