[package]
name = "uuid-cli"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretcehv@gmail.com>"]

[dependencies]
uuid = { version = "0.6.0", features = ["v4"] }
clipboard = "0.4.4"
clap = "2.30.0"

[[bin]]
name = "uuid"
path = "src/main.rs"