[package]
name = "uuid-cli"
version = "0.2.1"
authors = ["Kyle Gretchev <kgretcehv@gmail.com>"]
description = "Generate UUIDs"

[dependencies]
uuid = { version = "0.7.1", features = ["v4"] }
clipboard = "0.5.0"
structopt = "0.2.10"

[[bin]]
name = "uuid"
path = "src/main.rs"