[package]
name = "uuid-cli"
version = "0.2.1"
authors = ["Kyle Gretchev <kgretcehv@gmail.com>"]
description = "Generate UUIDs"
edition = "2018"

[dependencies]
uuid = { version = "0.8", features = ["v4"] }
clipboard = "0.5"
structopt = "0.3"

[[bin]]
name = "uuid"
path = "src/main.rs"